### ISSUE TITLE
[Bug]: No player outside admin ID can run commands.

### ISSUE THREAD

**Issue by igotfits1** [ErdbeerbaerLP/DiscordIntegration-Forge#452]
### What happened?

Any player that joins our discord can not run any commands, only the admins that have the ID from the config can run commands. Please assist.
I want regular discord users to be able to run TPS, List, Clear, etc.....
Even when having adminOnly = false, it still doesnt work it comes back with the bot saying: You dont have permissions to execute this command.

### Game Version

1.12

### What platform are you using?

Forge

### Platform version

1.12.2

### Config File

```toml
[[commands.customCommands]]
      name = "kick"
      description = "Kicks an player from the Server"
      mcCommand = "kick %player% %reason%"
      adminOnly = true
      hidden = false

        [[commands.customCommands.args]]
          name = "player"
          description = "The player to be kicked"
          optional = false

        [[commands.customCommands.args]]
          name = "reason"
          description = "Reason for the kick"
          optional = true

    [[commands.customCommands]]
      name = "stop"
      description = "Stops the server"
      mcCommand = "stop"
      adminOnly = true
      hidden = false
args = [    ]

    [[commands.customCommands]]
      name = "list"
      description = "Shows online players"
      mcCommand = "list"
      adminOnly = false
      hidden = false
args = [    ]

    [[commands.customCommands]]
      name = "tps"
      description = "Show server TPS"
      mcCommand = "forge tps"
      adminOnly = false
      hidden = false
args = [    ]

    [[commands.customCommands]]
      name = "clear"
      description = "Clear floor of items"
      mcCommand = "kill @e[type=item]"
      adminOnly = false
      hidden = false
args = [    ]

    [[commands.customCommands]]
      name = "wlremove"
      description = "Remove player from whitelist"
      mcCommand = "wl remove %target%"
      adminOnly = true
      hidden = false
args = [    ]

    [[commands.customCommands]]
      name = "kill"
      description = "Kills an Player or Entity"
      mcCommand = "kill %target%"
      adminOnly = true
      hidden = false

        [[commands.customCommands.args]]
          name = "target"
          description = "The target(s) for the kill command."
          optional = false
```
